[project]
name = "kalman-test"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "filterpy>=1.4.5",
    "ipykernel>=6.30.0",
    "numpy>=2.3.1",
    "ruff>=0.12.4",
    "seaborn>=0.13.2",
]
